export const ErrorCodes = {
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  UNKNOWN_TYPE: 'UNKNOWN_TYPE',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_TIMEOUT: 'AUTH_TIMEOUT',
  TIMEOUT: 'TIMEOUT',
  NOT_CONNECTED: 'NOT_CONNECTED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  DIRECTORY_NOT_FOUND: 'DIRECTORY_NOT_FOUND',
  CLI_NOT_FOUND: 'CLI_NOT_FOUND',
  ALREADY_CONNECTED: 'ALREADY_CONNECTED',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
